THX_ANALYTICAL_POSTGRES_DB_USERNAME = "dfsdf"
THX_ANALYTICAL_POSTGRES_DB_PASSWORD = "dsgsdg"

MEMO2_DEV_PROD_POSTGRES_DB_USERNAME = "fysdgfkjs"
MEMO2_DEV_PROD_POSTGRES_DB_PASSWORD = "jasHDJSA"


THX_ANALYTICAL_REDSHIFT_MASTER_USERNAME = "sfasdfafq"
THX_ANALYTICAL_REDSHIFT_MASTER_PASSWORD = "dflsdkf"